/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author chamara
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();

    }
    controller.Controller numberController = new Controller();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        decimalText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        binarylText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        octallText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hexaDecimalText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number System Controller");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        decimalText.setBackground(new java.awt.Color(102, 102, 102));
        decimalText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decimalText.setForeground(new java.awt.Color(204, 204, 204));
        decimalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        decimalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Decimal");

        binarylText.setBackground(new java.awt.Color(102, 102, 102));
        binarylText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        binarylText.setForeground(new java.awt.Color(204, 204, 204));
        binarylText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        binarylText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarylTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Binary");

        octallText.setBackground(new java.awt.Color(102, 102, 102));
        octallText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        octallText.setForeground(new java.awt.Color(204, 204, 204));
        octallText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        octallText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octallTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Octal");

        hexaDecimalText.setBackground(new java.awt.Color(102, 102, 102));
        hexaDecimalText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hexaDecimalText.setForeground(new java.awt.Color(204, 204, 204));
        hexaDecimalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hexaDecimalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexaDecimalTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HexaDecimal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(hexaDecimalText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(octallText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(binarylText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(decimalText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimalText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binarylText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(octallText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hexaDecimalText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void decimalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalTextActionPerformed
//        try {
            setNumbers(numberController.getNumberModel(decimalText.getText(),Controller.DECIMAL));
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Invalid Decimal number format. Please re-enter.");
//        }
    }//GEN-LAST:event_decimalTextActionPerformed

    private void binarylTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarylTextActionPerformed
//        try {
            setNumbers(numberController.getNumberModel(binarylText.getText(),Controller.BINARY));
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Invalid Binary number format. Please re-enter.");
//        }

    }//GEN-LAST:event_binarylTextActionPerformed

    private void octallTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octallTextActionPerformed
//        try {
            setNumbers(numberController.getNumberModel(octallText.getText(),Controller.OCTAL));
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Invalid Octal number format. Please re-enter.");
//        }
    }//GEN-LAST:event_octallTextActionPerformed

    private void hexaDecimalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexaDecimalTextActionPerformed
//        try {
            setNumbers(numberController.getNumberModel(hexaDecimalText.getText(),Controller.HEXA_DECIMAL));
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Invalid Hexa Decimal number format. Please re-enter.");
//        }
    }//GEN-LAST:event_hexaDecimalTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    private void setNumbers(model.Model numberModel) {
        decimalText.setText(numberModel.getDecimal());
        binarylText.setText(numberModel.getBinary());
        octallText.setText(numberModel.getOctal());
        hexaDecimalText.setText(numberModel.getHexaDecimal());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binarylText;
    private javax.swing.JTextField decimalText;
    private javax.swing.JTextField hexaDecimalText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField octallText;
    // End of variables declaration//GEN-END:variables
}
